name: Delivery setup
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  descriptor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: MojoTheApe/master-repo@__STANDARD_REVISION__
